apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-process-service
  namespace: nimble-platform
  labels:
    app: nimble-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-process-service
  template:
    metadata:
      labels:
        app: business-process-service
    spec:
      containers:
        - name: business-process-service
          image: nimbleplatform/business-process-service:latest
          env:
            - name: BUSINESS_PROCESS_DB_HOST
              value: "kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com"
            - name: BUSINESS_PROCESS_DB_PORT
              value: "25060"
            - name: BUSINESS_PROCESS_DB_NAME
              value: "businessprocessdb"
            - name: BUSINESS_PROCESS_DB_USERNAME
              value: "doadmin"
            - name: BUSINESS_PROCESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: business-process-service-secrets
                  key: BUSINESS_PROCESS_DB_PASSWORD
            - name: UBL_DB_HOST
              value: "kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com"
            - name: UBL_DB_HOST_PORT
              value: "25060"
            - name: UBL_DB_NAME
              value: "ubldb"
            - name: UBL_DB_USERNAME
              value: "doadmin"
            - name: UBL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: business-process-service-secrets
                  key: UBL_DB_PASSWORD
            - name: CAMUNDA_DB_HOST
              value: "kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com"
            - name: CAMUNDA_DB_PORT
              value: "25060"
            - name: CAMUNDA_DB_NAME
              value: "camundadb"
            - name: CAMUNDA_DB_USERNAME
              value: "doadmin"
            - name: CAMUNDA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: business-process-service-secrets
                  key: CAMUNDA_DB_PASSWORD
            - name: BINARY_CONTENT_DB_HOST
              value: "kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com"
            - name: BINARY_CONTENT_DB_PORT
              value: "25060"
            - name: BINARY_CONTENT_DB_NAME
              value: "binarycontentdb"
            - name: BINARY_CONTENT_DB_USERNAME
              value: "doadmin"
            - name: BINARY_CONTENT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: business-process-service-secrets
                  key: BINARY_CONTENT_DB_PASSWORD
            - name: BINARY_CONTENT_URL
              value: "http://not-yet-in-use/"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: KAFKA_JAAS_CONFIG
              value: ""
            - name: _JAVA_OPTIONS
              value: "-Xmx512m -Xms50m"
            - name: SMTP_HOST
              value: "maildev"
            - name: SMTP_PORT
              value: "25"
            - name: SMTP_DEFAULT_FROM
              value: "nimble@local-dev"
            - name: SMTP_USERNAME
              value: ""
            - name: SMTP_PASSWORD
              value: ""
            - name: SMTP_AUTH
              value: "false"
            - name: SMTP_STARTTLS
              value: "false"
            - name: BP_SERVICE_OAUTH_CLIENT_ID
              value: "bp-service-client"
            - name: BP_SERVICE_OAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: business-process-service-secrets
                  key: BP_SERVICE_OAUTH_SECRET
            - name: IDENTITY_SERVICE_URL
              value: "http://identity-service:9096/"
            - name: TRUST_SERVICE_URL
              value: "http://trust-service:9098/"
            - name: CONFIG_SERVER_URI
              value: "http://config-server:8888"
            - name: CONFIG_SERVER_FAILFAST
              value: "true"
            - name: DISCOVERY_ENABLED
              value: "true"
            - name: DISCOVERY_PREFER_IP
              value: "false"
            - name: DISCOVERY_SERVER_URI
              value: "http://service-discovery:8761"
            - name: BUSINESS_PROCESS_SERVICE_URL
              value: ""
            - name: DATA_CHANNEL_SERVICE_URL
              value: "http://data-channel-service:9099"
            - name: FRONTEND_URL
              value: "https://nimble.kolayam.co.uk"
            - name: FEDERATION_INSTANCE_ID
              value: ""
            - name: KAFKA_TOPIC_BUSINESS_PROCESS_UPDATES
              value: ""
            - name: KEYCLOAK_PUBLIC_KEY
              value: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg99CjKcp4Lm28juVmoe8nitA4yRdDOvQO5kzhPmUCSut9yyAYlJt9JNOFJMRs3zJoEd2JzpI9gBrQYWAQ8q/Uf13lQHDYPQATBdGt+eI7a0Cxl/NGRAOap56yg1KwWs89EIaTiAdQNiWLWXUAm5xA6MGEevBj/azbMofBpf4wjtJ6bFAEa5KGrfEuzMTxiWHNiM8F0ow17STJx5s/T+wqw6qZ+pK6pE1DvbZ0KDOyLCwBvYAMwd7tw5jmSjMnlOn3k1SoCDv9kt8/UL6AJMXMTQZFsyPuthPA/XidRlJCRGaoiNByfSoQExtlO5PkFeDy1vBsqRTL3cpIbVeDsP+JQIDAQAB"
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 2000Mi

---
kind: Service
metadata:
  name: business-process-service
  labels:
    app: nimble-platform
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8085
      targetPort: 8081
  selector:
    app: business-process-service
