apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-process-service
  namespace: nimble-platform
  labels:
    app: nimble-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-process-service
  template:
    metadata:
      labels:
        app: business-process-service
    spec:
      containers:
        - name: business-process-service
          image: rannybal2024/business-process-service:IMAGE_TAG
          env:
            - name: BUSINESS_PROCESS_DB_HOST
              value: "kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com"
            - name: BUSINESS_PROCESS_DB_PORT
              value: "25061"
            - name: BUSINESS_PROCESS_DB_NAME
              value: "businessprocessdb"
            - name: BUSINESS_PROCESS_DB_USERNAME
              value: "doadmin"
            - name: BUSINESS_PROCESS_DB_PASSWORD
              value: "AVNS_xN6h3TZAvlOwe4vdAdk"
            - name: UBL_DB_HOST
              value: "kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com"
            - name: UBL_DB_HOST_PORT
              value: "25061"
            - name: UBL_DB_NAME
              value: "ubldb"
            - name: UBL_DB_USERNAME
              value: "doadmin"
            - name: UBL_DB_PASSWORD
              value: "AVNS_xN6h3TZAvlOwe4vdAdk"
            - name: CAMUNDA_DB_HOST
              value: "kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com"
            - name: CAMUNDA_DB_PORT
              value: "25061"
            - name: CAMUNDA_DB_NAME
              value: "camundadb"
            - name: CAMUNDA_DB_USERNAME
              value: "doadmin"
            - name: CAMUNDA_DB_PASSWORD
              value: "AVNS_xN6h3TZAvlOwe4vdAdk"
            - name: BINARY_CONTENT_DB_HOST
              value: "kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com"
            - name: BINARY_CONTENT_DB_PORT
              value: "25061"
            - name: BINARY_CONTENT_DB_NAME
              value: "binarycontentdb"
            - name: BINARY_CONTENT_DB_USERNAME
              value: "doadmin"
            - name: BINARY_CONTENT_DB_PASSWORD
              value: "AVNS_xN6h3TZAvlOwe4vdAdk"
            - name: BINARY_CONTENT_URL
              value: "http://not-yet-in-use/"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap:9092"
            - name: KAFKA_JAAS_CONFIG
              value: ""
            - name: _JAVA_OPTIONS
              value: "-Xmx512m -Xms50m"
            - name: SMTP_HOST
              value: "smtp.gmail.com"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_DEFAULT_FROM
              value: "support@kolanot.co.uk"
            - name: SMTP_USERNAME
              value: "support@kolanot.co.uk"
            - name: SMTP_PASSWORD
              value: "lzuqcjludynkrtvd"
            - name: SMTP_AUTH
              value: "true"
            - name: SMTP_STARTTLS
              value: "true"
            - name: LOGSTASH_URI
              value: "logstash-service:5044"
            - name: BP_SERVICE_OAUTH_CLIENT_ID
              value: "bp-service-client"
            - name: BP_SERVICE_OAUTH_SECRET
              value: "621c1ec2-6753-4ead-925f-a5df24876a2b"
            - name: IDENTITY_SERVICE_URL
              value: "http://identity-service:9096/"
            - name: TRUST_SERVICE_URL
              value: "http://trust-service:9098/"
            - name: CONFIG_SERVER_URI
              value: "http://config-server:8888"
            - name: CONFIG_SERVER_FAILFAST
              value: "true"
            - name: DISCOVERY_ENABLED
              value: "true"
            - name: DISCOVERY_PREFER_IP
              value: "false"
            - name: DISCOVERY_SERVER_URI
              value: "http://service-discovery:8761"
            - name: EUREKA_CLIENT_HEALTHCHECK
              value: 'false'
            - name: BUSINESS_PROCESS_SERVICE_URL
              value: ""
            - name: DATA_CHANNEL_SERVICE_URL
              value: "http://data-channel-service:9099"
            - name: FRONTEND_URL
              value: "https://www.kolayam.co.uk"
            - name: FEDERATION_INSTANCE_ID
              value: "kerberos"
            - name: "DELEGATE_SERVICE_URL"
              value: "http://delegate-service:8080"
            - name: "TRACKING_ANALYSIS_SERVICE_URL"
              value: "http://tracking-analysis-service:8091"
            - name: KAFKA_TOPIC_BUSINESS_PROCESS_UPDATES
              value: ""
            - name: STRIPE_SECRET_KEY
              value: "sk_test_51NYrpWDm3eNdEyUnTxNx27CcIFD22jjnT3zqtt8MAQGzsP1oe6rGqdhQgsaZKR7EtOSPznIEw80rBE0G65jLEQ8I006Oy5RGOc"
            - name: KEYCLOAK_PUBLIC_KEY
              value: "-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjbTzPIh+ff5lTVW0c4veuS3Ers+29+h9mXXcwkojaDRwzHmf1ZCVvJY3eNy6NCu0SwVksA2tusBZK+qiSo4Kk24DDTNz1JQ7HDvXzTxH6Vfz8vPC9qq+kOPBqUOXctlNTiyz+8uEA6rS1ZpzcbVOdds0xx9k0pSlZhXxbeJlq+m8nS5cWNiAMnS4Z0UQDJXNL5Y8a4z8XTPlX5cv9B2cikQpQ97grnUQ1ihAs+7gw6Jo1DyU+6V1KEYK89yPtn8bSvsgVSIx0g97kBS7c2EhmqBgQ5h5zXW7nLXTiNE+va7Gk0Bfaf6jw5j8p5/uigrRlmgoTQxvgE7oiviJA18ZTQIDAQAB-----END PUBLIC KEY-----"
          ports:
            - containerPort: 8085
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 2000Mi
