apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nimble-platform
    name: business-process-service2
  name: business-process-service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nimble-platform
      name: business-process-service2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: nimble-platform
        name: business-process-service2
    spec:
      containers:
      - image: nimbleplatform/business-process-service2
        imagePullPolicy: Always
        name: business-process-service2
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: kubernetes
          - name: DISCOVERY_ENABLED
            value: "false"
          - name: DB_CREDENTIALS_JSON # Camunda database
            valueFrom:
              secretKeyRef:
                name: binding-nimble-camunda-db-prod
                key: binding
          - name: BLUEMIX_BUSINESS_PROCESS_DB_JSON
            valueFrom:
              secretKeyRef:
                name: binding-nimble-business-process-db-prod
                key: binding
          - name: BLUEMIX_UBL_DB_JSON
            valueFrom:
              secretKeyRef:
                name: binding-nimble-ubl-db-prod
                key: binding
          - name: BLUEMIX_MODAML_DB_JSON
            valueFrom:
              secretKeyRef:
                name: binding-nimble-modaml-db-prod
                key: binding
