apiVersion: v1
kind: Secret
metadata:
  name: business-process-service-secrets
  namespace: nimble-platform
type: Opaque
data:
  BUSINESS_PROCESS_DB_PASSWORD: QVZOU19xTjZoM1RaQXZsT3dlNHZkQWRr
  UBL_DB_PASSWORD: QVZOU19xTjZoM1RaQXZsT3dlNHZkQWRr
  CAMUNDA_DB_PASSWORD: QVZOU19xTjZoM1RaQXZsT3dlNHZkQWRr
  BINARY_CONTENT_DB_PASSWORD: QVZOU19xTjZoM1RaQXZsT3dlNHZkQWRr
  BP_SERVICE_OAUTH_SECRET: OTU3MGZlZTEtZjdhMi00OTIyLTg5MGQtNWY0OGNiNDY2NGM0
